---
url: "https://raw.githubusercontent.com/cosmos/cosmos-sdk/master/docs/sdk/lcd-rest-api.yaml"
dom_id: "#swagger-ui"
validatorUrl: "https://online.swagger.io/validator"
oauth2RedirectUrl: "http://localhost:3200/oauth2-redirect.html"
